/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface MaximillionInterface extends utils.Interface {
  functions: {
    "repayBehalf(address)": FunctionFragment;
    "repayBehalfExplicit(address,address)": FunctionFragment;
    "vBnb()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "repayBehalf" | "repayBehalfExplicit" | "vBnb"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "repayBehalf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "repayBehalfExplicit",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "vBnb", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "repayBehalf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayBehalfExplicit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vBnb", data: BytesLike): Result;

  events: {};
}

export interface Maximillion extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MaximillionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    repayBehalf(
      borrower: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    repayBehalfExplicit(
      borrower: PromiseOrValue<string>,
      vBnb_: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vBnb(overrides?: CallOverrides): Promise<[string]>;
  };

  repayBehalf(
    borrower: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  repayBehalfExplicit(
    borrower: PromiseOrValue<string>,
    vBnb_: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vBnb(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    repayBehalf(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    repayBehalfExplicit(
      borrower: PromiseOrValue<string>,
      vBnb_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    vBnb(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    repayBehalf(
      borrower: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    repayBehalfExplicit(
      borrower: PromiseOrValue<string>,
      vBnb_: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vBnb(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    repayBehalf(
      borrower: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    repayBehalfExplicit(
      borrower: PromiseOrValue<string>,
      vBnb_: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vBnb(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
